# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the jira8 branch
on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ github-actions ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1.4.2
        with:
          java-version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        
      - name: Build front
        run: |
              sudo sh -c 'echo "deb https://packages.atlassian.com/debian/atlassian-sdk-deb/ stable contrib" >> /etc/apt/sources.list'
              wget https://packages.atlassian.com/api/gpg/key/public
              sudo apt-key add public
              sudo apt-get update
              sudo apt-get install atlassian-plugin-sdk
              atlas-version
        
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Build atlas package
        run: atlas-package
  
      - name: Build front
        working-directory: js
        run: |
              yarn install
              yarn build-prod
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging

